from constants.prompt_template_en import _SYSTEM_PROMPT_EN, _BASIC_USER_PROMPT_EN, _IMPROVE_USER_PROMPT_EN, _FILL_IN_THE_BLANKS_USER_PROMPTS_EN, _NAMING_USER_PROMPTS_EN
from constants.prompt_template_jp import _SYSTEM_PROMPT_JP, _BASIC_USER_PROMPT_JP, _IMPROVE_USER_PROMPT_JP, _FILL_IN_THE_BLANKS_USER_PROMPTS_JP, _NAMING_USER_PROMPTS_JP, _CONVERSATIONAL_USER_PROMPTS_JP
from constants.prompt_template_nsfw import _SYSTEM_PROMPT_JP_NSFW

SYSTEM_PROMPTS = {
    "EN": _SYSTEM_PROMPT_EN,
    "JP": _SYSTEM_PROMPT_JP,
    "JP_NSFW": _SYSTEM_PROMPT_JP_NSFW,
}

BASIC_USER_PROMPTS = {
    "EN": _BASIC_USER_PROMPT_EN,
    "JP": _BASIC_USER_PROMPT_JP,
}

IMPROVE_USER_PROMPTS = {
    "EN": _IMPROVE_USER_PROMPT_EN,
    "JP": _IMPROVE_USER_PROMPT_JP,
}

FILL_IN_THE_BLANKS_USER_PROMPTS = {
    'EN': _FILL_IN_THE_BLANKS_USER_PROMPTS_EN,
    'JP': _FILL_IN_THE_BLANKS_USER_PROMPTS_JP,
}

NAMING_USER_PROMPTS = {
    'EN': _NAMING_USER_PROMPTS_EN,
    'JP': _NAMING_USER_PROMPTS_JP,
}

CONVERSATIONAL_USER_PROMPTS = {
    'JP': _CONVERSATIONAL_USER_PROMPTS_JP
}