[BASIC_USER_PROMPTS]
JP = '''
Seed: {seed}

リクエスト内容に基づきプロンプトを作成してください。
リクエストはテーマを示しており、必要な内容は想像して良いです。
また、出力フォーマット(<output_format>)で指示されている出力形式を厳密に守ってください。

<request>
{request}
</request>
'''

[IMPROVE_USER_PROMPTS]
JP = '''
Seed: {seed}

以下のプロンプト(input_prompt)の元のテーマ性を維持しつつ、イラストを改善してください。
例えば、プロンプトの整理だけでも良いですし、詳細な描写（例えば、状況、雰囲気、人物の外見、背景など）を加えたり、逆に要素を絞ってシンプルにしたりしても良いです。
また、出力フォーマット(<output_format>)で指示されている出力形式を厳密に守ってください。

<input_prompt>
{request}
</input_prompt>
'''

[FILL_IN_THE_BLANKS_USER_PROMPTS]
JP = '''
Seed: {seed}

以下のプロンプト(input_prompt)の「____」の部分を想像して、イラストを完成させてください。外見や状況、雰囲気など、具体的な内容を適宜盛り込んでください。「____」に入れる要素は、いくつでも構いません。
また、出力フォーマット(<output_format>)で指示されている出力形式を厳密に守ってください。

<input_prompt>
{request}
</input_prompt>
'''

[NAMING_USER_PROMPTS]
JP = '''
Seed: {seed}

以下のプロンプト(input_prompt)のタイトルとポイントを考えてください。
プロンプトは変更せずにオリジナルのまま記述し、出力フォーマット(<output_format>)で指示されている出力形式を厳密に守ってください。

<input_prompt>
{request}
</input_prompt>
'''

[CONVERSATIONAL_USER_PROMPTS]
JP = '''
リクエストと会話履歴をもとにプロンプトを作成してください。
リクエストはあくまでもテーマです。イラストに必要な内容は想像して追加してください。

<history>
{history}
</history>

<request>
{request}
</request>
'''